#!/bin/bash

echo "Do not install git versions"

paru wireshark-qt
paru inetutils
paru ubridge
paru libvirt
paru dynamips
paru vpcs
sudo pacman -S libvirt dnsmasq iptables-nft btrfs-progs
sudo pacman -S xterm
paru gns3-gui
paru gns3-server
sudo usermod -aG docker $USER
sudo usermod -aG libvirt $USER
sudo usermod -aG kvm $USER
sudo systemctl enable --now libvirtd.service
#sudo virsh net-start default starts the nat tunnel
