#!/bin/bash
sudo rm -f $(which paru)
rm -rf ~/.cargo/registry ~/.cargo/git
echo "installing paru"
sudo pacman -S --needed base-devel
rustup default stable
sudo pacman -S git
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
sudo rm -r paru
