#!/bin/bash

pkill waybar
sleep 0.2
hyprctl eval "hl.exec_cmd('waybar')"

pkill swaync
sleep 0.2
hyprctl eval "hl.exec_cmd('swaync')"

pkill batteryalert
sleep 0.2
hyprctl eval "hl.exec_cmd('batteryalert')"

pkill hyprshell
sleep 0.2
hyprctl eval "hl.exec_cmd('hyprshell-init')"

systemctl --user restart pipewire.service

hyprctl reload
