#!/bin/bash
pkill waybar
hyprctl dispatch exec waybar

pkill swaync
hyprctl dispatch exec swaync

pkill hyprswitch
hyprctl dispatch exec hyprswitchINIT

pkill batteryalert
hyprctl dispatch exec batteryalertL

pkill hyprshell
hyprctl dispatch exec hyprshell run

systemctl --user restart pipewire.servie
hyprctl reload
