#!/bin/bash

pkill waybar
sleep 0.2
hyprctl eval "hl.exec_cmd('waybar')"

pkill swaync
sleep 0.2
hyprctl eval "hl.exec_cmd('swaync')"

pkill hyprswitch
sleep 0.2
hyprctl eval "hl.exec_cmd('hyprswitch')"

pkill batteryalert
sleep 0.2
hyprctl eval "hl.exec_cmd('batteryalert')"

pkill hyprshell
sleep 0.2
hyprctl eval "hl.exec_cmd('hyprshell run')"

systemctl --user restart pipewire.service

hyprctl reload
