#!/bin/bash

CHOSEN=$(rofi -dmenu -p "CODE:")

case ${CHOSEN} in
"a")
  rofi -show drun -show-icons
  ;;
"p")
  rofi-powermenu
  ;;
"pd")
  systemctl poweroff
  ;;
"w")
  rofi-wifi-menu
  ;;
"l")
  hyprlock
  ;;
"c")
  kitty -e nvim
  ;;
"co")
  rofi-set-select-config
  ;;
"web")
  cd ~/Projects/hyprlinkwindow/ && npm start
  ;;
"wal")
  rofi-set-wal
  ;;
"emo")
  rofi -show emoji --action clipboard
  ;;
"cal")
  rofi -show calc -no-show-match -no-sort
  ;;
"tw")
  toggle-waybar
  ;;
"ro")
  python ~/Games/RobloxAccountManagerLinux/main.py
  ;;
"gamo")
  game-net-optimize
  ;;
"code")
  code
  ;;
"update")
  kitty -e paru-update && flatpak update
  ;;
"mikb")
  ~/Appps/Winbox_Linux/Winbox
  ;;
esac
