#!/bin/bash
mkdir -p ~/.cache/walset/wallcurrent
rm ~/.cache/walset/wallcurrent/wallpaper.jpg
cp $1 ~/.cache/walset/wallcurrent/wallpaper.jpg
rm -r ~/.cache/wal/schemes
mkdir ~/.cache/wal/schemes
awww img ~/.cache/walset/wallcurrent/wallpaper.jpg --transition-type wipe
wal -a 92 -i ~/.cache/walset/wallcurrent/wallpaper.jpg

#reload apps that does not auto update themes
resetHyprland
