[LINK]
NAME: youtube
URL: youtube.com

[LINK]
NAME: deadeye power dps
URL: snowcrows.com/builds/accessibuilds/thief/power-deadeye

[LINK]
NAME: 4k wallpaper
URL: 4kwallpapers.com

[LINK]
URL: https://www.youtube.com/watch?v=HTAfWBAIHwU
NAME: roadmap to anime art

[LINK]
NAME: anime drawing series prof
URL: https://www.youtube.com/watch?v=vhXiqx4g-iM&list=PLy8mZW3dyYeCY1ve7uG75p4goXlshDmVM

[LINK]
URL: https://www.youtube.com/watch?v=6J0czKZauJw&list=PLg3y1PTl09VTngKDD0bneVyLXOa6gYHHP
NAME: anime art drawing series

[LINK]
NAME: guild wars 2 event timer
URL: https://wiki.guildwars2.com/wiki/Event_timers

[LINK]
NAME: eldorado
URL: https://www.eldorado.gg

[LINk]
NAME: twitch
URL: www.twitch.tv/

[LINK]
NAME: fitgirl repacks
URL: https://www.fitgirl-repacks.site

[LINK]
NAME: torrent downloads pro
URL: torrentdownloads.pro

[LINK]
NAME: ext
URL: ext.to

[LINK]
NAME: dream gaming PC
URL: https://www.evetech.co.za/ryzen-7-9700x-rx-9070-gaming-pc-pbs/best-pc-deal/22472

[LINK]
NAME: evetech
URL: https://www.evetech.co.za/

[LINK]
NAME: TOME
URL: https://te4.org

[LINK]
NAME: grok
URL: grok.com

[LINK]
NAME: api list
URL: https://apilist.fun/

[LINK]
NAME: .gitignore preconfig
URL: https://github.com/github/gitignore

[LINK]
NAME: Reaper - Power Greatsword Reaper 
URL: https://metabattle.com/wiki/Build:Reaper_-_Power_Greatsword_Reaper#google_vignette

[LINK]
NAME: Luminary - Bunker Luminary
URL: https://metabattle.com/wiki/Build:Luminary_-_Bunker_Luminary

[LINK]
NAME: Hybrid DPS/Healer ritualist build
URL: https://www.youtube.com/watch?v=U4SBX0_H8tc&themeRefresh=1

[LINK]
NAME: w3school bash docs
URL: https://www.w3schools.com/bash

[LINK]
NAME: ws3schools python docs
URL: https://www.w3schools.com/python
